### PR TITLE
Add support for unfurl_links & unfurl_media

### PR DESCRIPTION
**Pull request by Pyppe**
As specificed in https://api.slack.com/methods/chat.postMessage

### CODE REVIEW

**Review by mccartney — APPROVED** [review]
Looks fine. Thanks for the contribution.

**Comment by Pyppe** [comment]
Thank you! What’s the schedule for a new release containing this?

**Comment by mccartney** [comment]
Nothing scheduled. I can make sure the release happens when I find a minute. I can see you need it.

**Comment by mccartney** [comment]
`0.2.12` has been just released. Sorry for keeping you waiting, I didn't find time earlier around Christmas.

**Comment by Pyppe** [comment]
Great, thank you! However, as I tried to utilize the new functionality, I just noticed it wasn't exposed in the `SlackRtmClient`. 🤦 Sorry about that! See https://github.com/slack-scala-client/slack-scala-client/pull/166

**Pull request merged**
