### PR TITLE
Api client refactor

### PR DESCRIPTION
**Pull request by tg44**
I made commits along the way of the refactoring process, but the whole can be squashed too.
What I did;
 - created a taggless final trait as SlackApiClientF (this gets a wrapper (like Future) as typeparam) and checked that it was successful or not (and fixed some differences between the blocking and async impl)
 - removed/auto generated the blocking api
 - the requesting logic is moved out to a separated class (I like smaller classes)
 - made extract to an extender method (opinionated if it worth or not, but until this commit everything is binary compatible with the previous lib version)
 - racionalized the implicits
   - removed all the system.dispacher (it is not a good practice)
   - removed the implicit actorsystem from the def params (do we need to let the user to use our lib on different `as`s? using more than one as in an app is discuraged anyway)
   - added implicit `ec` and `as` to the "creator" methods
   - removed the materializers (not a good practice to create them on the way, also `as` can be used as an implicit `mat`)
   - this can broke bin-comp, but probably will not break user code

Random thoughts;
 - If we could break bin-comp, I would move the random classes in random files either to an object or a separated package... (I hate multipurpose files, also a 900 line long scala file is not so healthy)
 - I would probably split the api-client to multiple smaller traits/classes to make it smaller/understandable
 - I would split/move most of the things from the `SlackApiClient` object
 - I would not use the blocking implementation in the `SlackRtmConnectionActor`
 - probably if we would move the "tagless final magic" to the requester, we could generalize the api-client, making the scope of the "magic" smaller :D

### CODE REVIEW

**Comment by mccartney** [comment]
Wow. That's an enormous contribution. Thank you for spending the time.

I'd need to spend more time on this, but immediate thoughts are:
- I'd rather have smaller PRs, but good that you kept commits separate. I think I need to review commit by commit
- I am uncertain about introducing cats (which I have never worked with), it seems like a non-trivial dependency, which would impact all the uses of the library. Not sure what do we get as the benefit.

**Comment by mccartney** [comment]
Also - why would we care about binary compatibility between various versions of this library? I don't think we ever had before.

**Comment by tg44** [comment]
Cats is widely used, and not that big as a dependency I think. Akka is so much bigger. I only use Id[_] from it. So nobody has to deal with it inside or outside of the code if not want to. If you watch the PR commit by commit I think its straightforward what did I do :) Most of my mods was just find and replace ;) Also the autogenrated blocking implementation is oneof the newly added libs "readme".

As a library author we not really like to break apis, bcs if we do that the lib users need to change their code if they want to upgrade our lib version. Bin-comp is when you do changes without breaking the public interface. (For example adding a new param to a function is breaking the api, but if it has default value it will not.)

**Comment by tg44** [comment]
I rebased to fix the 2.13 build, also found out that [cats-tagless](https://github.com/typelevel/cats-tagless) is not build for 2.11 so I dropped 2.11 for now :( I didn't notice that this lib was also compiled to 2.11, probably this will invalidate some parts of the PR.

I think if we want to keep 2.11 (which I assume) I can move forward with this with making the ApiRequester to tagless final too, implement the blocking requester by hand, moving the Id/Future abstraction one layer deeper. And if I implement the blocking api requester by hand, I can remove the cats-tagless dep, use cats-core 2.0.0 (which still build to 2.11), and still narrowing the repeated code.

**Pull request closed without merging**
